### ISSUE TITLE
麻烦看下文章内容有没有问题（OpenCV计算机视觉学习（6）——图像梯度计算&边缘检测（Sobel算子，scharr算法，Laplacian算子，Canny算子））

### ISSUE THREAD

**Issue by Mythos-Rudy** [LeBron-Jian/ComputerVisionPractice#1]
https://www.cnblogs.com/wj-1314/p/9800272.html
兄弟，下面这部分 prewitt和sobel是不是写反了啊

> _1.6  Sobel算子，Robert算子，prewitt算子的比较
> 　　Sobel算子是滤波算子的形式来提取边缘，X，Y方向各用一个模板，两个模板组合起来构成一个梯度算子。X方向模板对垂直边缘影响最大，Y方向模板对水平边缘影响最大。
> 
> 　　Robert算子是一种梯度算子，它用交叉的查分表示梯度，是一种利用局部差分算子寻找边缘的算子，对具有陡峭的低噪声的图像效果最好。
> 
> 　　prewitt算子是加权平均算子，对噪声有抑制作用，但是像素平均相当于对图像进行的同滤波，所以prewitt算子对边缘的定位不如robert算子。_

**Comment by LeBron-Jian** [comment]
没问题，兄弟。
首先，Prewitt算子和Sobel算子都是一阶微分算子，Sobel算子是在Prewitt算子的基础上增加了权重的概念。
你是不是觉得 “**prewitt算子是加权平均算子**”这句话有问题。应该是说Prewitt算子对噪声抑制是通过像素平均来实现的。

**Comment by Mythos-Rudy** [comment]
是的，我理解的是，sobel的权重分别是1,2,1，所以是加权平均，prewitt是直接平均，没有加权，所以会觉得这句话有点问题，没事儿，大家都理解到位就好了，文章写得很详细，佩服佩服~

**Comment by LeBron-Jian** [comment]
对对对，理解到位就OK，我这也是做的笔记，欢迎指正！！！
