### ISSUE TITLE
大佬，像那种银行卡、身份证四角有弧度的要怎么处理呢，有好的解决思路吗？

### ISSUE THREAD

**Issue by yangy996** [LeBron-Jian/ComputerVisionPractice#2]

**Comment by LeBron-Jian** [comment]
个人建议，你可以使用轮廓将其圈出来，之后，进行轮廓近似，这样就可以将弧度处理掉。你可以参考我这篇博客：https://www.cnblogs.com/wj-1314/p/11510789.html（OpenCV计算机视觉学习（8）——图像轮廓处理（轮廓绘制，轮廓检索，轮廓填充，轮廓近似））

里面主要做的笔记就是：轮廓绘制，轮廓检索，轮廓填充，轮廓近似
