### ISSUE TITLE
您好，我想问一下，像那种俯拍的图片有什么方法可以矫正吗？

### ISSUE THREAD

**Issue by FYF1997** [LeBron-Jian/ComputerVisionPractice#3]
具体图片的描述为：一个竖着的黑板，然后正上方有一个摄像头，拍出来的是一个畸形的图片，我试过自己矫正，但是效果不是很好，需要您的帮助，我的联系邮箱为：1548670824@qq.com。谢谢您！

**Comment by LeBron-Jian** [comment]
你的目的是什么？俯视拍出来的畸形图片要识别里面的东西吗？
