### ISSUE TITLE
高人，请问如何在照片中定位一个特定的形状，并计算其位置和转角？

### ISSUE THREAD

**Issue by sxbug** [LeBron-Jian/ComputerVisionPractice#4]
照片的拍照距离和位置可以调整，但是背景比较复杂。想在照片中将特定的形状（一个切了部分的圆）找出来，并标记其的转角（以切口水平为0度转角）。
![gun2](https://user-images.githubusercontent.com/20074137/105620261-ff092880-5e35-11eb-8974-42dbe0df4c71.jpg)

**Comment by sxbug** [comment]
我想做到的效果，就是把照片中的类似形状标记出来，并标记 它在照片中的位置和转角。
![Uploading gun3.jpg…]()

**Comment by sxbug** [comment]
请问有好办法吗？查找边界的很多办法就是边界模糊。用sift就是无法将模型与照片匹配。总之问题较多，请指教

**Comment by LeBron-Jian** [comment]
我不是高人哈，就是一个学习者，首先你发的图片我看不了，然后你说的这种，假设图像处理效果不是很好地话，可以使用深度学习目标检测，也可以使用模板匹配（如果太复杂，可能此方法无效）；
